In [4]:
import numpy as np

# Task 01

number_of_elem = 10
start_elem = 0
print(np.arange((number_of_elem - 1), (start_elem - 1), -1))

# a bit different solution

print(np.linspace(start = 9, stop = 0, num = 10, endpoint = True, dtype = int))

[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


In [6]:
# Task 02

number_of_elem = 6
start_elem = 0
d_array = np.diag(np.arange((number_of_elem - 1), (start_elem - 1), -1), k = 0)
print(d_array)                                      
print("Сумма значений элементов на диагонали ", np.trace(d_array))


[[5 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
Сумма значений элементов на диагонали  15


In [9]:
# Task 03

# resolving a set of linear equations

AA = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
bb = np.array([4, 12, -3])
xx = np.linalg.solve(AA, bb)
print("Система уравнения имеет следующее решение: ")
print("x = ",xx[0]," y = ",xx[1]," z = ",xx[2])

# to check the solution
print(np.allclose(np.dot(AA, xx), bb))



Система уравнения имеет следующее решение: 
x =  0.4666666666666668  y =  3.844444444444444  z =  -5.555555555555555
True


In [11]:
# Task 04

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ],
    np.int32
)
next_user_stats = np.array([0,1,2,0,0,0])

list_results = []
for element in users_stats:
    cos1 = np.dot(element, next_user_stats) / (np.sqrt(np.dot(element,element)) * np.sqrt(np.dot(next_user_stats,next_user_stats)))
    list_results.append(cos1)

print(f"The highest cosine similarity {max(list_results)} is between the new visitor and user with ID ", (list_results.index(max(list_results)))+1)



The highest cosine similarity 0.9486832980505138 is between the new visitor and user with ID  8
